version: '3.7'
services:
  db:
    image: mysql:5.7.22
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /var/lib/mysql
    ports:
      - 8082:3306
    environment:
      MYSQL_DATABASE: 'akelpetin_cv'
      MYSQL_USER: 'akelpetin'
      MYSQL_PASSWORD: 'development'
      MYSQL_ROOT_PASSWORD: 'root'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: 'root'
      PMA_PASSWORD: 'root'
    ports:
      - 8882:80
    depends_on:
      - db
volumes:
  db_data: {}